name: EnvironmentDeploymentWorkflow

on:
  push:
    branches: ["main"]

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    container: gradle:8.4-jdk17
    steps:
      - name: add azure artifacts credentials to gradle properties
        run: |
          mkdir ~/.gradle
          echo adelynflowersUsername=$AZURE_ARTIFACTS_USERNAME >> ~/.gradle/gradle.properties
          echo adelynflowersPassword=$AZURE_ARTIFACTS_PASSWORD >> ~/.gradle/gradle.properties
      - name: checkout repo
        uses: actions/checkout@v4.1.1

      - name: build and unit test with gradle
        run: gradle build --no-daemon

      - name: run integration tests
        run: gradle integrationTest --no-daemon

      - name: upload jar to azure artifacts
        run: gradle publish

      - name: build docker image
        run: gradle bootBuildImage

      - name: authenticate with azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: upload docker image to container registry
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr login --name adelynflowers
            docker push $(gradle -q printName):$(gradle -q printVersion)      

  qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: test
    steps:

      - name: wip upload to azure
        run: echo "uploaded to azure"

