name: EnvironmentDeploymentWorkflow

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  test-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: authenticate with azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: add azure artifacts credentials to gradle properties
        env:
          AZURE_ARTIFACTS_USERNAME: ${{ secrets.AZURE_ARTIFACTS_USERNAME }}
          AZURE_ARTIFACTS_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PASSWORD }}
        run: |
          mkdir ~/.gradle;
          echo adelynflowersUsername=$AZURE_ARTIFACTS_USERNAME >> ~/.gradle/gradle.properties;
          echo adelynflowersPassword=$AZURE_ARTIFACTS_PASSWORD >> ~/.gradle/gradle.properties

      - name: checkout repo
        uses: actions/checkout@v4.1.1

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Remove default github maven configuration
        # This step is a workaround to avoid a decryption issue of github's provided maven
        # settings.xml file
        run: rm ~/.m2/settings.xml

      - name: build and unit test with gradle
        run: ./gradlew build --no-daemon

      - name: run integration tests
        run: ./gradlew integrationTest --no-daemon

      - name: upload jar to azure artifacts
        run: ./gradlew publish

      - name: build docker image
        run: gradle bootBuildImage

      - name: upload docker image to container registry
        run: |
            az acr login --name adelynflowers;
            docker tag $(gradle -q printName):$(gradle -q printVersion) adelynflowers.azurecr.io/$(gradle -q printName):$(gradle -q printVersion);
            docker push adelynflowers.azurecr.io/$(gradle -q printName):$(gradle -q printVersion);
            echo adelynflowers.azurecr.io/$(gradle -q printName):$(gradle -q printVersion) > image_id.txt

      - name: upload image name as artifact
        uses: actions/upload-artifact@v3
        with:
          name: image_id
          path: ./image_id.txt

  qa:
    runs-on: ubuntu-latest
    needs: test-and-upload
    steps:

      - name: authenticate with azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: checkout repo
        uses: actions/checkout@v4.1.1

      - name: download image_id artifact
        uses: actions/download-artifact@v3
        with:
          name: image_id
          path: terraform/image_id.txt


      - name: deploy instance and save ip
        run: |
          ls -a;
          cd terraform;
          ls -a;
          terraform init;
          terraform plan -var "image=$(cat image_id.txt)" -out "main.tfplan";
          terraform apply "main.tfplan"

      - name: curl instance
        run: |
          cd terraform;
          echo "$(terraform output -raw container_ipv4_address):8080/" > instance_ip;
          curl $(cat instance_ip);

      - name: shutdown resources
        run: |
          cd terraform;
          terraform plan -var "image=$(cat image_id.txt)" -destroy -out main.destroy.tfplan;
          terraform apply "main.destroy.tfplan"
          
          
          
      
          

