name: EnvironmentDeploymentWorkflow

on:
  push:
    branches: ["main"]

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    container: gradle:8.4-jdk17
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1

      - name: build and unit test with gradle
        run: gradle build --no-daemon

      - name: run integration tests
        run: gradle integrationTest --no-daemon

      - name: upload jar to azure artifacts
        run: |
          echo adelynflowersUsername=$AZURE_ARTIFACTS_USERNAME >> ~/.gradle/gradle.properties
          echo adelynflowersPassword=$AZURE_ARTIFACTS_PASSWORD >> ~/.gradle/gradle.properties
          gradle publish

  qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: test
    steps:

      - name: checkout repo
        uses: actions/checkout@v4.1.1

      - name: wip upload to azure
        run: echo "uploaded to azure"

