# Runs test linting on pull requests to main

name: PRWorkflow

on:
  pull_request:
      branches: [ main ]
  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    container: gradle:8.4-jdk17
    steps:
    - name: checkout repo
      uses: actions/checkout@v4.1.1
  
    - name: build and test with gradle
      run: |
        gradle build --no-daemon
    

